### PR TITLE
Add long polling support

### PR DESCRIPTION
**Pull request by dacamo76**
Adds long polling support to receive message requests.

A short description from the [SDK javadoc](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sqs/model/ReceiveMessageRequest.html#withWaitTimeSeconds%28java.lang.Integer%29) describing advantages of long polling.

> Long poll support is enabled by using the WaitTimeSeconds parameter. For more information, see Amazon SQS Long Poll in the [Amazon SQS Developer Guide](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-long-polling.html) .
> Short poll is the default behavior where a weighted random set of machines is sampled on a ReceiveMessage call. This means only the messages on the sampled machines are returned. If the number of messages in the queue is small (less than 1000), it is likely you will get fewer messages than you requested per ReceiveMessage call. If the number of messages in the queue is extremely small, you might not receive any messages in a particular ReceiveMessage response; in which case you should repeat the request.

### CODE REVIEW

**Comment by dacamo76** [comment]
Reviewing the code again, I think wait-time-seconds doesn't adequately describe what the option does.

I chose the same name used in the AWS SDK thinking a one-to-one translation would make things easier, but now I'm thinking it might force users to dig into the SQS docs.

The `receive` function uses the option name `:limit` in place of the SDK parameter `MaxNumberOfMessages`. Similarly, a more descriptive name for `wait-time-seconds` would be easier for users to grasp, especially those not familiar with the SDK. Maybe something like `:empty-queue-wait`. What do you think?

**Comment by dacamo76** [comment]
Hi @cemerick I know you aren't actively contributing to this project anymore, but could you take a quick look at this pull request if you get a chance.

**Comment by cemerick** [comment]
Sorry for the long delay. Merged, thanks. I'm releasing version `0.0.6` now, which should show up in maven central later this morning.

**Comment by cemerick** [comment]
If you could put together a PR adding a small usage example for this to the README, that'd be great.

**Comment by dacamo76** [comment]
Thanks. I've added a simple usage example to the README. #11

**Pull request merged**
